### ISSUE TITLE
Fails to build on Mac due to certificate signing

### ISSUE THREAD

**Issue by hippietrail** [jcgamestoy/retrovm1#1]
I'm new to Mac programming but I did Google and check StackOverflow for what to do before asking here. So sorry if it would be obvious how to proceed. I am building other Mac projects from github OK though and never saw this before:

Build target Retro Virtual Machine of project Retro Virtual Machine with configuration Debug
error: There are no accounts registered with Xcode. Add your developer account to Xcode (in target 'Retro Virtual Machine' from project 'Retro Virtual Machine')
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "TNP49M7S5T" with a private key was found. (in target 'Retro Virtual Machine' from project 'Retro Virtual Machine')
/Users/hippietrail/retrovm1/Retro Virtual Machine.xcodeproj: warning: OpenGL is deprecated. Consider migrating to Metal instead. (in target 'Retro Virtual Machine' from project 'Retro Virtual Machine')

----

Repair target Retro Virtual Machine

Diagnose problem
No "Mac Development" signing certificate matching team ID "TNP49M7S5T" with a private key was found.

----

By the way, when can we expect version 3?

**Comment by jcgamestoy** [comment]
I forgot to remove my signing ID. 

I fixed it, re-clone the repository and try again, confirm me that it works.

Thank you

**Comment by jcgamestoy** [comment]
I forgot to remove my signing ID. 

I fixed it, re-clone the repository and try again, confirm me that it works.

Thank you

**Comment by hippietrail** [comment]
Confirmed working. Thank you!
